# Generated by Django 6.1.1 on 2026-10-06 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoRecuperacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=64)),
                ("usado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_recuperacao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "codigo_recuperacao",
                "indexes": [
                    models.Index(
                        fields=["usuario", "hash"], name="ix_codrec_usuario_hash"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DispositivoTOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segredo_cifrado", models.TextField()),
                ("confirmado_em", models.DateTimeField(blank=True, null=True)),
                ("ultimo_passo", models.BigIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispositivos_totp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "dispositivo de verificação",
                "db_table": "dispositivo_totp",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("confirmado_em__isnull", False)),
                        fields=("usuario",),
                        name="uq_totp_um_ativo_por_usuario",
                    )
                ],
            },
        ),
    ]
