# Generated by Django 6.1.1 on 2026-10-05 16:58

import apps.atendimento.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('zona', models.CharField(choices=[('CEN', 'Centro'), ('NOR', 'Zona Norte'), ('SUL', 'Zona Sul'), ('LES', 'Zona Leste'), ('DIS', 'Distrito')], max_length=3)),
            ],
            options={
                'db_table': 'bairro',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('sigla', models.CharField(max_length=15, unique=True)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'db_table': 'secretaria',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimento.bairro')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimento.secretaria')),
            ],
            options={
                'db_table': 'area_atuacao',
            },
        ),
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Use apenas 11 dígitos.'), apps.atendimento.models.validar_cpf])),
                ('nome_completo', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moradores', to='atendimento.bairro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cidadao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cidadao',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('prazo_dias', models.PositiveSmallIntegerField(default=15)),
                ('ativa', models.BooleanField(default=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='atendimento.secretaria')),
            ],
            options={
                'db_table': 'categoria_servico',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='bairro',
            name='secretarias',
            field=models.ManyToManyField(related_name='bairros_atendidos', through='atendimento.AreaAtuacao', to='atendimento.secretaria'),
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servidores', to='atendimento.secretaria')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'servidor',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.TextField()),
                ('endereco_referencia', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ABE', 'Aberta'), ('ANA', 'Em análise'), ('EXE', 'Em execução'), ('CON', 'Concluída'), ('IND', 'Indeferida')], default='ABE', max_length=3)),
                ('prioridade', models.PositiveSmallIntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=2)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='atendimento.bairro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='atendimento.categoriaservico')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='atendimento.cidadao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_atribuidas', to='atendimento.servidor')),
            ],
            options={
                'db_table': 'solicitacao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('ABE', 'Aberta'), ('ANA', 'Em análise'), ('EXE', 'Em execução'), ('CON', 'Concluída'), ('IND', 'Indeferida')], max_length=3)),
                ('status_novo', models.CharField(choices=[('ABE', 'Aberta'), ('ANA', 'Em análise'), ('EXE', 'Em execução'), ('CON', 'Concluída'), ('IND', 'Indeferida')], max_length=3)),
                ('observacao', models.TextField(blank=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='atendimento.solicitacao')),
            ],
            options={
                'db_table': 'historico_solicitacao',
                'ordering': ['registrado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriaservico',
            constraint=models.UniqueConstraint(fields=('secretaria', 'nome'), name='uq_categoria_por_secretaria'),
        ),
        migrations.AddConstraint(
            model_name='categoriaservico',
            constraint=models.CheckConstraint(condition=models.Q(('prazo_dias__gte', 1)), name='ck_categoria_prazo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='bairro',
            constraint=models.UniqueConstraint(fields=('nome', 'zona'), name='uq_bairro_nome_zona'),
        ),
        migrations.AddConstraint(
            model_name='areaatuacao',
            constraint=models.UniqueConstraint(fields=('secretaria', 'bairro'), name='uq_area_secretaria_bairro'),
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['status', 'prioridade'], name='ix_solic_status_prior'),
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['bairro', 'status'], name='ix_solic_bairro_status'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('concluida_em__isnull', False), ('status', 'CON')), models.Q(models.Q(('status', 'CON'), _negated=True), ('concluida_em__isnull', True)), _connector='OR'), name='ck_solic_conclusao_coerente'),
        ),
    ]
