# Generated by Django 6.1.1 on 2026-10-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='status_anterior',
            field=models.CharField(choices=[('ABE', 'Aberta'), ('ANA', 'Em análise'), ('EXE', 'Em execução'), ('CON', 'Concluída'), ('IND', 'Indeferida'), ('CAN', 'Cancelada pelo cidadão')], max_length=3),
        ),
        migrations.AlterField(
            model_name='historicosolicitacao',
            name='status_novo',
            field=models.CharField(choices=[('ABE', 'Aberta'), ('ANA', 'Em análise'), ('EXE', 'Em execução'), ('CON', 'Concluída'), ('IND', 'Indeferida'), ('CAN', 'Cancelada pelo cidadão')], max_length=3),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('ABE', 'Aberta'), ('ANA', 'Em análise'), ('EXE', 'Em execução'), ('CON', 'Concluída'), ('IND', 'Indeferida'), ('CAN', 'Cancelada pelo cidadão')], default='ABE', max_length=3),
        ),
    ]
