# Generated by Django 6.1.1 on 2026-10-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_alter_historicosolicitacao_status_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='termo_aceito_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
