# Generated by Django 6.1.1 on 2026-10-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_cidadao_termo_aceito_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='email_confirmado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
