# Generated by Django 6.1.1 on 2026-10-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_cidadao_email_confirmado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidadao',
            name='receber_avisos',
            field=models.BooleanField(default=True),
        ),
    ]
