# Generated by Django 6.1.1 on 2026-10-06 22:55

import apps.atendimento.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0005_cidadao_receber_avisos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(height_field='altura', upload_to=apps.atendimento.models.caminho_foto, width_field='largura')),
                ('etapa', models.CharField(choices=[('PRO', 'Foto do problema'), ('SER', 'Foto do serviço realizado')], default='PRO', max_length=3)),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('largura', models.PositiveIntegerField(default=0)),
                ('altura', models.PositiveIntegerField(default=0)),
                ('tamanho', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'foto_solicitacao',
                'ordering': ['enviada_em', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__gte', -90), ('latitude__isnull', False), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__isnull', False), ('longitude__lte', 180)), _connector='OR'), name='ck_solic_coordenadas'),
        ),
        migrations.AddField(
            model_name='fotosolicitacao',
            name='enviada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fotosolicitacao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='atendimento.solicitacao'),
        ),
    ]
